- name: "setup jumpbox"
  hosts: jumpbox
  tasks:
    - name: "modify dns"
      lineinfile:
        path: /etc/resolv.conf
        line: "nameserver 8.8.8.8"
        create: yes
      become: true
      become_user: root
    - name: "update system"
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
      become: true
      become_user: root
    - name: "install cli utilities"
      package:
        name:
          - wget
          - curl
          - vim
          - openssl
          - git
        state: latest
      become: true
      become_user: root
    - name: "create git folder"
      file:
        path: "~/git/"
        state: directory
        mode: '0750'
    - name: "clone kubernetes the hard way"
      git:
        repo: "https://github.com/kelseyhightower/kubernetes-the-hard-way.git"
        depth: 1
        dest: "~/git/kubernetes-the-hard-way"
    - name: "download k8 binaries"
      shell:
        cmd: |
          set -e 
          processed_urls=$(cat downloads.txt | sed 's/arm64/amd64/g')
          for url in ${processed_urls}; do
            wget -q --show-progress --https-only --timestamping -P binaries "${url}"
          done
        chdir: ~/git/kubernetes-the-hard-way
        creates: binaries
    - name: "make kubectl binary executable"
      file:
        path: "~/git/kubernetes-the-hard-way/binaries/kubectl"
        mode: "0750"
    - name: "copy kubectl binary"
      copy:
        src: "{{ ansible_env.HOME }}/git/kubernetes-the-hard-way/binaries/kubectl"
        dest: "/usr/local/bin/kubectl"
        owner: root
        group: root
        mode: '0755'
        remote_src: true
      become: true
